name: Rust Formatter

on: [push, pull_request]

jobs:
  rust-fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Rustfmt Check
      run: cargo fmt --all -- --check
